### ISSUE TITLE
No other option for format?

### ISSUE THREAD

**Issue by Nicxe** [Kaptensanders/skolmat#4]
Version 2.0 removes the option to get only one course as sate, is there now another way of doing that in the integration? 

The possibility to only TTS-notify the children with one course instead of two makes a huge difference.

**Comment by Kaptensanders** [comment]
Hi Nicxxe, yes it was deprecated as there was no consistency between kitchens in the number of courses and vegetarian alternative etc. Initially it seemed to be two courses where the second was veg, but I have since discovered that some shools list up to four courses soo it makes no sense to keep the previous format setting.

Anyway, the courses are separated by a newline character, so you can split and pick yourself if your school have a consistent way of sorting them
